/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Firefly_6.glb --transform 
Files: Firefly_6.glb [1.21MB] > /home/kevin-s/javascript/antinoob-demo/public/Firefly_6-transformed.glb [81.75KB] (93%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Firefly_6(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Firefly_6-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty006" position={[2.719, 0.509, 7.7]} rotation={[-3.118, -0.234, 2.375]} scale={0.05}>
          <mesh name="firefly026" geometry={nodes.firefly026.geometry} material={materials['Material.003']} position={[0.053, 0.258, -0.166]} rotation={[0, -0.207, 0]} scale={[0.134, 0.128, 0.281]} />
          <mesh name="firefly027" geometry={nodes.firefly027.geometry} material={materials['Material.003']} position={[0.103, 0.155, -0.188]} rotation={[0, 0.108, 0]} scale={[0.13, 0.128, 0.284]} />
          <mesh name="firefly028" geometry={nodes.firefly028.geometry} material={materials['Material.003']} position={[-0.028, 0.259, -0.153]} rotation={[0, -0.827, 0]} scale={[0.234, 0.128, 0.206]} />
          <mesh name="firefly029" geometry={nodes.firefly029.geometry} material={materials['Material.003']} position={[-0.039, 0.155, -0.19]} rotation={[0, -0.13, 0]} scale={[0.131, 0.128, 0.283]} />
          <group name="firefly025" position={[0.023, -0.105, 0.012]} scale={[0.128, 0.128, 0.284]}>
            <mesh name="firefly025_1" geometry={nodes.firefly025_1.geometry} material={materials['firfly_mtrl:firefly_diffSG']} />
            <mesh name="firefly025_2" geometry={nodes.firefly025_2.geometry} material={materials.aiStandard4SG} />
            <mesh name="firefly025_3" geometry={nodes.firefly025_3.geometry} material={materials.blinn1SG} />
            <mesh name="firefly025_4" geometry={nodes.firefly025_4.geometry} material={materials['Material.003']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Firefly_6-transformed.glb')
