/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Firefly_5.glb --transform 
Files: Firefly_5.glb [1.22MB] > /home/kevin-s/javascript/antinoob-demo/public/Firefly_5-transformed.glb [81.44KB] (93%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Firefly_5(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Firefly_5-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty005" position={[2.719, 0.509, 7.7]} rotation={[-3.118, -0.234, 2.375]} scale={0.05}>
          <mesh name="firefly021" geometry={nodes.firefly021.geometry} material={materials['Material.003']} position={[0.053, 0.258, -0.166]} rotation={[0, -0.073, 0]} scale={[0.129, 0.128, 0.284]} />
          <mesh name="firefly022" geometry={nodes.firefly022.geometry} material={materials['Material.003']} position={[0.103, 0.155, -0.188]} scale={[0.128, 0.128, 0.284]} />
          <mesh name="firefly023" geometry={nodes.firefly023.geometry} material={materials['Material.003']} position={[-0.028, 0.259, -0.153]} rotation={[0, -0.906, 0]} scale={[0.247, 0.128, 0.191]} />
          <mesh name="firefly024" geometry={nodes.firefly024.geometry} material={materials['Material.003']} position={[-0.039, 0.155, -0.19]} scale={[0.128, 0.128, 0.284]} />
          <group name="firefly020" position={[0.023, -0.105, 0.012]} scale={[0.128, 0.128, 0.284]}>
            <mesh name="firefly020_1" geometry={nodes.firefly020_1.geometry} material={materials['firfly_mtrl:firefly_diffSG']} />
            <mesh name="firefly020_2" geometry={nodes.firefly020_2.geometry} material={materials.aiStandard4SG} />
            <mesh name="firefly020_3" geometry={nodes.firefly020_3.geometry} material={materials.blinn1SG} />
            <mesh name="firefly020_4" geometry={nodes.firefly020_4.geometry} material={materials['Material.003']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Firefly_5-transformed.glb')
