/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Firefly_1.glb --transform 
Files: Firefly_1.glb [1.21MB] > /home/kevin-s/javascript/antinoob-demo/public/Firefly_1-transformed.glb [83.16KB] (93%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Firefly_1(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Firefly_1-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty003" position={[-3.108, -0.718, 7.932]} rotation={[-3.118, -0.233, 2.374]} scale={[0.317, 0.317, 0.143]}>
          <mesh name="firefly011" geometry={nodes.firefly011.geometry} material={materials['Material.003']} position={[0.053, 0.258, -0.166]} rotation={[0, -0.207, 0]} scale={[0.134, 0.128, 0.281]} />
          <mesh name="firefly012" geometry={nodes.firefly012.geometry} material={materials['Material.003']} position={[0.103, 0.155, -0.188]} rotation={[0, 0.108, 0]} scale={[0.13, 0.128, 0.284]} />
          <mesh name="firefly013" geometry={nodes.firefly013.geometry} material={materials['Material.003']} position={[-0.028, 0.259, -0.153]} rotation={[0, -0.827, 0]} scale={[0.234, 0.128, 0.206]} />
          <mesh name="firefly014" geometry={nodes.firefly014.geometry} material={materials['Material.003']} position={[-0.039, 0.155, -0.19]} rotation={[0, -0.13, 0]} scale={[0.131, 0.128, 0.283]} />
          <group name="firefly010" position={[0.023, -0.105, 0.012]} scale={[0.128, 0.128, 0.284]}>
            <mesh name="firefly010_1" geometry={nodes.firefly010_1.geometry} material={materials['firfly_mtrl:firefly_diffSG']} />
            <mesh name="firefly010_2" geometry={nodes.firefly010_2.geometry} material={materials.aiStandard4SG} />
            <mesh name="firefly010_3" geometry={nodes.firefly010_3.geometry} material={materials.blinn1SG} />
            <mesh name="firefly010_4" geometry={nodes.firefly010_4.geometry} material={materials['Material.003']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Firefly_1-transformed.glb')
