/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Firefly_3.glb --transform 
Files: Firefly_3.glb [1.22MB] > /home/kevin-s/javascript/antinoob-demo/public/Firefly_3-transformed.glb [91.55KB] (92%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Firefly_3(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Firefly_3-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty002" position={[-2.523, 0.815, 7.957]} rotation={[-2.943, -0.137, -2.773]} scale={0.05}>
          <group name="firefly001" position={[0.023, -0.105, 0.012]} scale={[0.128, 0.128, 0.284]}>
            <mesh name="firefly001_1" geometry={nodes.firefly001_1.geometry} material={materials['firfly_mtrl:firefly_diffSG']} />
            <mesh name="firefly001_2" geometry={nodes.firefly001_2.geometry} material={materials.aiStandard4SG} />
            <mesh name="firefly001_3" geometry={nodes.firefly001_3.geometry} material={materials.blinn1SG} />
            <mesh name="firefly001_4" geometry={nodes.firefly001_4.geometry} material={materials['Material.003']} />
          </group>
          <mesh name="firefly006" geometry={nodes.firefly006.geometry} material={materials['Material.003']} position={[0.053, 0.258, -0.166]} rotation={[0, -0.199, 0]} scale={[0.134, 0.128, 0.282]} />
          <mesh name="firefly007" geometry={nodes.firefly007.geometry} material={materials['Material.003']} position={[0.103, 0.156, -0.188]} rotation={[0, 0.108, 0]} scale={[0.13, 0.128, 0.284]} />
          <mesh name="firefly008" geometry={nodes.firefly008.geometry} material={materials['Material.003']} position={[-0.028, 0.259, -0.153]} rotation={[0, -0.831, 0]} scale={[0.235, 0.128, 0.205]} />
          <mesh name="firefly009" geometry={nodes.firefly009.geometry} material={materials['Material.003']} position={[-0.039, 0.155, -0.19]} rotation={[0, -0.123, 0]} scale={[0.13, 0.128, 0.283]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Firefly_3-transformed.glb')
