/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./demo_bg/Main_Land_2.glb --transform 
Files: ./demo_bg/Main_Land_2.glb [163.62MB] > /home/kevin-s/javascript/antinoob-demo/public/Main_Land_2-transformed.glb [11.67MB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Main_Land_2(props) {
  const { nodes, materials } = useGLTF('/Main_Land_2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Generator003_1.geometry} material={materials['Forest Ground.001']} />
      <mesh geometry={nodes.Generator003_2.geometry} material={materials['Grass.001']} />
    </group>
  )
}

useGLTF.preload('/Main_Land_2-transformed.glb')
