/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./demo_bg/Main_Land_4.glb --transform 
Files: ./demo_bg/Main_Land_4.glb [265.39MB] > /home/kevin-s/javascript/antinoob-demo/public/Main_Land_4-transformed.glb [20.14MB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Main_Land_4(props) {
  const { nodes, materials } = useGLTF('/Main_Land_4-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Generator005_1.geometry} material={materials['Forest Ground.001']} />
      <mesh geometry={nodes.Generator005_2.geometry} material={materials['Grass.001']} />
    </group>
  )
}

useGLTF.preload('/Main_Land_4-transformed.glb')
