/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./demo_bg/Main_Land_3.glb --transform 
Files: ./demo_bg/Main_Land_3.glb [249.33MB] > /home/kevin-s/javascript/antinoob-demo/public/Main_Land_3-transformed.glb [19MB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Main_Land_3(props) {
  const { nodes, materials } = useGLTF('/Main_Land_3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Generator004_1.geometry} material={materials['Forest Ground.001']} />
      <mesh geometry={nodes.Generator004_2.geometry} material={materials['Grass.001']} />
    </group>
  )
}

useGLTF.preload('/Main_Land_3-transformed.glb')
