/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 demo_bg/Oranges.glb --transform 
Files: demo_bg/Oranges.glb [4.15MB] > /home/kevin-s/javascript/antinoob-demo/public/Oranges-transformed.glb [1.27MB] (69%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Oranges(props) {
  const { nodes, materials } = useGLTF('/Oranges-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.946, 0.455, 8.1]} rotation={[-1.565, -1.237, -0.79]} scale={11.498}>
        <mesh geometry={nodes.Orange001.geometry} material={materials.Orange} />
        <mesh geometry={nodes.Orange001_1.geometry} material={materials['leaf old']} />
        <mesh geometry={nodes.Orange001_2.geometry} material={materials['Branch.014']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Oranges-transformed.glb')
