/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Scene_1_Main_Land_1.glb --transform 
Files: Scene_1_Main_Land_1.glb [84.05MB] > /home/kevin-s/javascript/antinoob-demo/public/Scene_1_Main_Land_1-transformed.glb [4.57MB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene_1_Main_Land_1(props) {
  const { nodes, materials } = useGLTF('/Scene_1_Main_Land_1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Generator002_1.geometry} material={materials['Forest Ground.001']} />
      <mesh geometry={nodes.Generator002_2.geometry} material={materials['Grass.001']} />
    </group>
  )
}

useGLTF.preload('/Scene_1_Main_Land_1-transformed.glb')
