/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 demo_bg/Scene_1_Main_Land_trees.glb --transform 
Files: demo_bg/Scene_1_Main_Land_trees.glb [117.61MB] > /home/kevin-s/javascript/antinoob-demo/public/Scene_1_Main_Land_trees-transformed.glb [5.79MB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene_1_Main_Land_trees(props) {
  const { nodes, materials } = useGLTF('/Scene_1_Main_Land_trees-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Generator002.geometry} material={materials['Forest Ground.002']} />
      <mesh geometry={nodes.Generator002_1.geometry} material={materials['Wood.002']} />
      <mesh geometry={nodes.Generator002_2.geometry} material={materials['Tree Branch.002']} />
    </group>
  )
}

useGLTF.preload('/Scene_1_Main_Land_trees-transformed.glb')
