/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Scene_1_Main_Land.glb --transform 
Files: Scene_1_Main_Land.glb [49.58MB] > /home/kevin-s/javascript/antinoob-demo/public/Scene_1_Main_Land-transformed.glb [1.34MB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene_1_Main_Land(props) {
  const { nodes, materials } = useGLTF('/Scene_1_Main_Land-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Generator006.geometry} material={materials['Forest Ground.002']} />
    </group>
  )
}

useGLTF.preload('/Scene_1_Main_Land-transformed.glb')
